In [42]:
import pandas as pd

In [43]:
geo_dataset = pd.read_csv("/Users/kristivanmeter/Desktop/MIDS/Capstone/DECENNIALDHC2020.P9_2024-02-09T095003/DECENNIALDHC2020.csv")

/var/folders/z2/38w7d0t53n9_7n4mywgz6phc0000gn/T/ipykernel_1811/2766297126.py:1: DtypeWarning: Columns (2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74) have mixed types. Specify dtype option on import or set low_memory=False.
  geo_dataset = pd.read_csv("/Users/kristivanmeter/Desktop/MIDS/Capstone/DECENNIALDHC2020.P9_2024-02-09T095003/DECENNIALDHC2020.csv")

In [44]:
geo_dataset.head(5)

# columns = list(dataset.columns)
# print(columns)

,GEO_ID,NAME,P9_001N,P9_002N,P9_003N,P9_004N,P9_005N,P9_006N,P9_007N,P9_008N,...,P9_065N,P9_066N,P9_067N,P9_068N,P9_069N,P9_070N,P9_071N,P9_072N,P9_073N,Unnamed: 75
0,Geography,Geographic Area Name,!!Total:,!!Total:!!Hispanic or Latino,!!Total:!!Not Hispanic or Latino:,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,!!Total:!!Not Hispanic or Latino:!!Population...,NaN
1,860Z200US00601,ZCTA5 00601,17242,17185,57,47,37,1,0,0,...,0,0,0,0,0,0,0,0,0,NaN
2,860Z200US00602,ZCTA5 00602,37548,37278,270,249,213,10,3,10,...,0,0,0,0,0,0,0,0,0,NaN
3,860Z200US00603,ZCTA5 00603,49804,48996,808,748,584,80,5,49,...,0,0,0,0,0,0,0,0,0,NaN
4,860Z200US00606,ZCTA5 00606,5009,4974,35,30,26,1,0,2,...,0,0,0,0,0,0,0,0,0,NaN

In [45]:
meta = pd.read_csv("/Users/kristivanmeter/Desktop/MIDS/Capstone/DECENNIALDHC2020.P9_2024-02-09T095003/DECENNIALDHC2020.P9-Column-Metadata.csv")
#meta

In [46]:
# cleaning

# Remove the first row with labels
geo_data = geo_dataset.iloc[1:]

# Display the DataFrame without the first row
print(geo_data)

               GEO_ID         NAME P9_001N P9_002N P9_003N P9_004N P9_005N  \
1      860Z200US00601  ZCTA5 00601   17242   17185      57      47      37
2      860Z200US00602  ZCTA5 00602   37548   37278     270     249     213
3      860Z200US00603  ZCTA5 00603   49804   48996     808     748     584
4      860Z200US00606  ZCTA5 00606    5009    4974      35      30      26
5      860Z200US00610  ZCTA5 00610   25731   25489     242     222     179
...               ...          ...     ...     ...     ...     ...     ...
33770  860Z200US99923  ZCTA5 99923      66       2      64      62      59
33771  860Z200US99925  ZCTA5 99925     784      14     770     650     293
33772  860Z200US99926  ZCTA5 99926    1562      46    1516    1320     151
33773  860Z200US99927  ZCTA5 99927      49       2      47      43      42
33774  860Z200US99929  ZCTA5 99929    2079      75    2004    1720    1321

      P9_006N P9_007N P9_008N  ... P9_065N P9_066N P9_067N P9_068N P9_069N  \
1           1       0       0  ...       0       0       0       0       0
2          10       3      10  ...       0       0       0       0       0
3          80       5      49  ...       0       0       0       0       0
4           1       0       2  ...       0       0       0       0       0
5          19       0       5  ...       0       0       0       0       0
...       ...     ...     ...  ...     ...     ...     ...     ...     ...
33770       0       0       0  ...       0       0       0       0       0
33771       4     345       8  ...       0       0       0       0       0
33772       4    1161       0  ...       1       0       1       0       0
33773       0       0       0  ...       0       0       0       0       0
33774       0     361      25  ...       0       0       0       0       0

      P9_070N P9_071N P9_072N P9_073N Unnamed: 75
1           0       0       0       0         NaN
2           0       0       0       0         NaN
3           0       0       0       0         NaN
4           0       0       0       0         NaN
5           0       0       0       0         NaN
...       ...     ...     ...     ...         ...
33770       0       0       0       0         NaN
33771       0       0       0       0         NaN
33772       0       0       0       0         NaN
33773       0       0       0       0         NaN
33774       0       0       0       0         NaN

[33774 rows x 76 columns]

In [47]:
# create geo_data copy
geo_data_copy = geo_data.copy()

part_black_cols = ["P9_006N", "P9_013N", "P9_018N", "P9_019N", "P9_020N", "P9_021N", 
                  "P9_029N", "P9_030N", "P9_031N", "P9_032N", "P9_039N", "P9_040N", 
                  "P9_041N", "P9_042N", "P9_043N", "P9_044N", "P9_050N", "P9_051N", 
                  "P9_052N", "P9_053N", "P9_054N", "P9_055N", "P9_060N", "P9_061N", 
                  "P9_062N", "P9_063N", "P9_066N", "P9_067N", "P9_068N", "P9_071N", 
                  "P9_073N"]

# Convert selected columns to numeric type
geo_data_copy[part_black_cols] = geo_data_copy[part_black_cols].apply(pd.to_numeric, errors='coerce')

# Sum the selected columns row-wise
geo_data_copy['part_black'] = geo_data_copy[part_black_cols].sum(axis=1)

# Display the DataFrame with the new column
print(geo_data_copy)

               GEO_ID         NAME P9_001N P9_002N P9_003N P9_004N P9_005N  \
1      860Z200US00601  ZCTA5 00601   17242   17185      57      47      37
2      860Z200US00602  ZCTA5 00602   37548   37278     270     249     213
3      860Z200US00603  ZCTA5 00603   49804   48996     808     748     584
4      860Z200US00606  ZCTA5 00606    5009    4974      35      30      26
5      860Z200US00610  ZCTA5 00610   25731   25489     242     222     179
...               ...          ...     ...     ...     ...     ...     ...
33770  860Z200US99923  ZCTA5 99923      66       2      64      62      59
33771  860Z200US99925  ZCTA5 99925     784      14     770     650     293
33772  860Z200US99926  ZCTA5 99926    1562      46    1516    1320     151
33773  860Z200US99927  ZCTA5 99927      49       2      47      43      42
33774  860Z200US99929  ZCTA5 99929    2079      75    2004    1720    1321

       P9_006N P9_007N P9_008N  ... P9_066N P9_067N P9_068N P9_069N  P9_070N  \
1            1       0       0  ...       0       0       0       0        0
2           10       3      10  ...       0       0       0       0        0
3           80       5      49  ...       0       0       0       0        0
4            1       0       2  ...       0       0       0       0        0
5           19       0       5  ...       0       0       0       0        0
...        ...     ...     ...  ...     ...     ...     ...     ...      ...
33770        0       0       0  ...       0       0       0       0        0
33771        4     345       8  ...       0       0       0       0        0
33772        4    1161       0  ...       0       1       0       0        0
33773        0       0       0  ...       0       0       0       0        0
33774        0     361      25  ...       0       0       0       0        0

      P9_071N P9_072N P9_073N Unnamed: 75  part_black
1           0       0       0         NaN           3
2           0       0       0         NaN          17
3           0       0       0         NaN         100
4           0       0       0         NaN           1
5           0       0       0         NaN          22
...       ...     ...     ...         ...         ...
33770       0       0       0         NaN           1
33771       0       0       0         NaN           9
33772       0       0       0         NaN          31
33773       0       0       0         NaN           0
33774       0       0       0         NaN          18

[33774 rows x 77 columns]

In [48]:
# change P9_005N into numeric value
geo_data_copy["P9_005N"] = pd.to_numeric(geo_data_copy["P9_005N"])

# create a new column that contains the value of P9_005N divided by part_black
geo_data_copy["white_black"] = geo_data_copy["P9_005N"] / geo_data_copy["part_black"]

print(geo_data_copy.head(5))

           GEO_ID         NAME P9_001N P9_002N P9_003N P9_004N  P9_005N  \
1  860Z200US00601  ZCTA5 00601   17242   17185      57      47       37
2  860Z200US00602  ZCTA5 00602   37548   37278     270     249      213
3  860Z200US00603  ZCTA5 00603   49804   48996     808     748      584
4  860Z200US00606  ZCTA5 00606    5009    4974      35      30       26
5  860Z200US00610  ZCTA5 00610   25731   25489     242     222      179

   P9_006N P9_007N P9_008N  ... P9_067N P9_068N P9_069N P9_070N  P9_071N  \
1        1       0       0  ...       0       0       0       0        0
2       10       3      10  ...       0       0       0       0        0
3       80       5      49  ...       0       0       0       0        0
4        1       0       2  ...       0       0       0       0        0
5       19       0       5  ...       0       0       0       0        0

  P9_072N P9_073N Unnamed: 75 part_black  white_black
1       0       0         NaN          3    12.333333
2       0       0         NaN         17    12.529412
3       0       0         NaN        100     5.840000
4       0       0         NaN          1    26.000000
5       0       0         NaN         22     8.136364

[5 rows x 78 columns]

In [49]:
# remove ZCTA5 from all values in the name column
geo_data_copy['NAME'] = geo_data_copy['NAME'].str.replace('ZCTA5 ', '')

print(geo_data_copy.head(5))

           GEO_ID   NAME P9_001N P9_002N P9_003N P9_004N  P9_005N  P9_006N  \
1  860Z200US00601  00601   17242   17185      57      47       37        1
2  860Z200US00602  00602   37548   37278     270     249      213       10
3  860Z200US00603  00603   49804   48996     808     748      584       80
4  860Z200US00606  00606    5009    4974      35      30       26        1
5  860Z200US00610  00610   25731   25489     242     222      179       19

  P9_007N P9_008N  ... P9_067N P9_068N P9_069N P9_070N  P9_071N P9_072N  \
1       0       0  ...       0       0       0       0        0       0
2       3      10  ...       0       0       0       0        0       0
3       5      49  ...       0       0       0       0        0       0
4       0       2  ...       0       0       0       0        0       0
5       0       5  ...       0       0       0       0        0       0

  P9_073N Unnamed: 75 part_black  white_black
1       0         NaN          3    12.333333
2       0         NaN         17    12.529412
3       0         NaN        100     5.840000
4       0         NaN          1    26.000000
5       0         NaN         22     8.136364

[5 rows x 78 columns]

In [57]:
# DIVERSITY INDEX

# change columns needed into numeric value
geo_data_copy["P9_002N"] = pd.to_numeric(geo_data_copy["P9_002N"])
geo_data_copy["P9_001N"] = pd.to_numeric(geo_data_copy["P9_001N"])
geo_data_copy["P9_005N"] = pd.to_numeric(geo_data_copy["P9_005N"])
geo_data_copy["P9_006N"] = pd.to_numeric(geo_data_copy["P9_006N"])
geo_data_copy["P9_007N"] = pd.to_numeric(geo_data_copy["P9_007N"])
geo_data_copy["P9_008N"] = pd.to_numeric(geo_data_copy["P9_008N"])
geo_data_copy["P9_009N"] = pd.to_numeric(geo_data_copy["P9_009N"])
geo_data_copy["P9_010N"] = pd.to_numeric(geo_data_copy["P9_010N"])
geo_data_copy["P9_011N"] = pd.to_numeric(geo_data_copy["P9_011N"])

# Create a new column for the proportion of Hispanic/Latino
geo_data_copy['prop_hisp_latino'] = geo_data_copy['P9_002N'] / geo_data_copy['P9_001N']

# Create a new column for the proportion of White alone
geo_data_copy['prop_white_alone'] = geo_data_copy['P9_005N'] / geo_data_copy['P9_001N']

# Create a new column for the proportion of Black alone
geo_data_copy['prop_black_alone'] = geo_data_copy['P9_006N'] / geo_data_copy['P9_001N']

# Create a new column for the proportion of American Indian/Alaska Native alone
geo_data_copy['prop_amer_ind_alone'] = geo_data_copy['P9_007N'] / geo_data_copy['P9_001N']

# Create a new column for the proportion of Asian alone
geo_data_copy['prop_asian_alone'] = geo_data_copy['P9_008N'] / geo_data_copy['P9_001N']

# Create a new column for the proportion of Native Hawaiian/Other Pacific Islander alone
geo_data_copy['prop_native_hawaiian_alone'] = geo_data_copy['P9_009N'] / geo_data_copy['P9_001N']

# Create a new column for the proportion of Some Other Race (SOR) alone
geo_data_copy['prop_sor_alone'] = geo_data_copy['P9_010N'] / geo_data_copy['P9_001N']

# Create a new column for the proportion of Two or More Races alone
geo_data_copy['prop_two_plus_alone'] = geo_data_copy['P9_011N'] / geo_data_copy['P9_001N']

# print(geo_data_copy.sample(5))

In [130]:
# Calculate the squares of proportions for each racial group
geo_data_copy['hisp_latino_sq'] = geo_data_copy['prop_hisp_latino'] ** 2
geo_data_copy['white_sq'] = geo_data_copy['prop_white_alone'] ** 2
geo_data_copy['black_sq'] = geo_data_copy['prop_black_alone'] ** 2
geo_data_copy['amer_ind_sq'] = geo_data_copy['prop_amer_ind_alone'] ** 2
geo_data_copy['asian_sq'] = geo_data_copy['prop_asian_alone'] ** 2
geo_data_copy['nhpi_sq'] = geo_data_copy['prop_native_hawaiian_alone'] ** 2
geo_data_copy['sor_sq'] = geo_data_copy['prop_sor_alone'] ** 2
geo_data_copy['two_plus_sq'] = geo_data_copy['prop_two_plus_alone'] ** 2

# Sum up the squared proportions for all racial groups
geo_data_copy['sum_sq'] = geo_data_copy[['hisp_latino_sq', 'white_sq', 'black_sq', 
                                         'amer_ind_sq', 'asian_sq', 'nhpi_sq', 
                                         'sor_sq', 'two_plus_sq']].sum(axis=1)

# Calculate diversity index
geo_data_copy['diversity_index'] = 1 - geo_data_copy['sum_sq']

# Drop intermediate columns
geo_data_copy.drop(columns=['hisp_latino_sq', 'white_sq', 'black_sq', 
                            'amer_ind_sq', 'asian_sq', 'nhpi_sq', 
                            'sor_sq', 'two_plus_sq', 'sum_sq'], inplace=True)

# Print the DataFrame to see the diversity index column
print(geo_data_copy[['NAME', 'diversity_index']].sample(5))

        NAME  diversity_index
19174  55953         0.163161
9790   30055         0.240379
25438  72430         0.091388
12810  38647         0.482495
8787   27889         0.561272

In [131]:
# keep only columns NAME, white_black, diversity_index
final = geo_data_copy[['NAME', 'white_black', 'diversity_index']]

#final.to_csv('final.csv', index=False)

In [132]:
# upload Faces and Names dataset

faces_dataset = pd.read_csv('/Users/kristivanmeter/Desktop/MIDS/Capstone/unique_participants_newfaces.csv')
faces_dataset

,Unnamed: 0.1,Unnamed: 0,block_order,block_name,stimuli,valence,random_fixation,movement,accuracy,response_time,...,Avg Total RT Avoid Female,Avg Total RT Approach Black,Avg Total RT Avoid Black,Avg Total RT Approach White,Avg Total RT Avoid White,Openness,Conscientiousness,Extraversion,Agreeableness,Neuroticism
0,0,60,1,blkTestCatAAp,47,2,1900,Avoid,1,1384,...,870.000000,950.900000,1002.4,781.2,978.900000,3.75,4.75,2.75,4.00,1.50
1,40,160,1,blkTestCatAAp,32,1,1500,Approach,1,519,...,594.900000,651.400000,571.5,480.5,680.700000,4.50,3.75,2.50,3.50,1.50
2,80,260,1,blkTestCatAAp,43,2,1200,Avoid,1,828,...,675.900000,628.200000,657.1,718.0,648.800000,2.25,4.25,2.00,3.00,1.50
3,120,360,1,blkTestCatAAp,63,2,1500,Avoid,1,1224,...,1125.500000,1150.800000,1069.0,1107.9,1113.800000,5.00,3.50,3.75,4.75,1.75
4,160,460,1,blkTestCatAAp,51,2,800,Avoid,1,5188,...,934.600000,1028.333333,1335.6,734.2,883.777778,3.00,5.00,2.50,4.00,2.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,13477,35860,1,blkTestCatAAp,60,2,900,Approach,1,729,...,568.300000,591.400000,0.0,0.0,560.700000,4.25,3.50,3.50,3.75,1.50
358,13517,35960,1,blkTestCatAAp,27,1,1300,Avoid,1,497,...,658.300000,593.200000,0.0,0.0,644.800000,3.50,3.50,3.50,3.25,3.75
359,13557,36060,1,blkTestCatAAp,59,2,1500,Approach,1,519,...,533.500000,494.315789,0.0,0.0,534.400000,4.75,4.00,4.75,4.25,2.75
360,13596,36160,1,blkTestCatAAp,39,1,2000,Avoid,1,552,...,906.900000,691.684211,0.0,0.0,847.650000,4.50,3.75,3.50,4.00,2.00
361,13635,36260,1,blkTestCatAAp,57,2,1600,Approach,1,726,...,646.333333,646.833333,0.0,0.0,641.285714,3.75,4.00,2.00,3.25,2.50

In [133]:
# make copy of faces_dataset
faces_dataset = faces_dataset.copy()

# Add '0' as the first digit to ensure all values have 5 digits in Zip
faces_dataset.loc[faces_dataset["Zip"].astype(str).str.len() < 5, "Zip"] = faces_dataset["Zip"].astype(str).str.zfill(5)


# reset index after filtering
faces_dataset.reset_index(drop=True, inplace=True)

In [134]:
# Convert 'NAME' column in final and 'Zip' column in faces_dataset to int64
final['NAME'] = final['NAME'].astype('int64').copy()
faces_dataset['Zip'] = faces_dataset['Zip'].astype('int64').copy()

/var/folders/z2/38w7d0t53n9_7n4mywgz6phc0000gn/T/ipykernel_1811/2037437165.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['NAME'] = final['NAME'].astype('int64').copy()

In [135]:

# Merge datasets based on 'Zip' column with a left join
merged_df = pd.merge(faces_dataset, final, left_on='Zip', right_on='NAME', how='left')

# Update 'white_black' values where there's a match
merged_df['white_black'] = merged_df['white_black'].fillna(0)  # Fill NaN values with 0

# Drop the extra 'NAME' column
merged_df.drop(columns=['NAME'], inplace=True)

merged_df

,Unnamed: 0.1,Unnamed: 0,block_order,block_name,stimuli,valence,random_fixation,movement,accuracy,response_time,...,Avg Total RT Avoid Black,Avg Total RT Approach White,Avg Total RT Avoid White,Openness,Conscientiousness,Extraversion,Agreeableness,Neuroticism,white_black,diversity_index
0,0,60,1,blkTestCatAAp,47,2,1900,Avoid,1,1384,...,1002.4,781.2,978.900000,3.75,4.75,2.75,4.00,1.50,14.813487,0.486712
1,40,160,1,blkTestCatAAp,32,1,1500,Approach,1,519,...,571.5,480.5,680.700000,4.50,3.75,2.50,3.50,1.50,60.740741,0.244615
2,80,260,1,blkTestCatAAp,43,2,1200,Avoid,1,828,...,657.1,718.0,648.800000,2.25,4.25,2.00,3.00,1.50,16.007435,0.461046
3,120,360,1,blkTestCatAAp,63,2,1500,Avoid,1,1224,...,1069.0,1107.9,1113.800000,5.00,3.50,3.75,4.75,1.75,133.571429,0.064736
4,160,460,1,blkTestCatAAp,51,2,800,Avoid,1,5188,...,1335.6,734.2,883.777778,3.00,5.00,2.50,4.00,2.75,0.187739,0.612749
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,13477,35860,1,blkTestCatAAp,60,2,900,Approach,1,729,...,0.0,0.0,560.700000,4.25,3.50,3.50,3.75,1.50,0.747627,0.646600
358,13517,35960,1,blkTestCatAAp,27,1,1300,Avoid,1,497,...,0.0,0.0,644.800000,3.50,3.50,3.50,3.25,3.75,121.000000,0.037341
359,13557,36060,1,blkTestCatAAp,59,2,1500,Approach,1,519,...,0.0,0.0,534.400000,4.75,4.00,4.75,4.25,2.75,93.731250,0.159188
360,13596,36160,1,blkTestCatAAp,39,1,2000,Avoid,1,552,...,0.0,0.0,847.650000,4.50,3.75,3.50,4.00,2.00,8.504742,0.436649
361,13635,36260,1,blkTestCatAAp,57,2,1600,Approach,1,726,...,0.0,0.0,641.285714,3.75,4.00,2.00,3.25,2.50,0.501697,0.674659

In [136]:
# write merged data
merged_df.to_csv('merged_faces.csv', index=False)

In [137]:
# upload Faces and Names dataset

names_dataset = pd.read_csv('/Users/kristivanmeter/Desktop/MIDS/Capstone/unique_participants_newnames.csv')
names_dataset

,Unnamed: 0.1,Unnamed: 0,block_order,block_name,stimuli,valence,random_fixation,movement,accuracy,response_time,...,Avg Total RT Avoid Female,Avg Total RT Approach Black,Avg Total RT Avoid Black,Avg Total RT Approach White,Avg Total RT Avoid White,Openness,Conscientiousness,Extraversion,Agreeableness,Neuroticism
0,0,10,1,blkTestCatAAp,40,1,1200,Avoid,1,653,...,706.200000,877.0,705.300000,906.700000,721.8,4.00,3.75,3.00,3.50,3.00
1,40,110,1,blkTestCatAAp,61,2,1900,Approach,1,6601,...,1194.000000,1559.0,1192.500000,1236.200000,1417.3,3.50,4.00,4.25,3.25,2.50
2,80,210,1,blkTestCatAAp,34,1,1900,Avoid,1,1262,...,1274.857143,1115.7,1028.000000,951.875000,1231.5,3.50,3.50,3.25,2.25,3.00
3,113,310,1,blkTestCatAAp,47,2,1000,Approach,1,1895,...,756.900000,790.8,694.300000,761.200000,735.1,3.75,4.75,4.50,4.75,2.50
4,153,410,1,blkTestCatAAp,49,2,1300,Approach,1,415,...,577.900000,555.2,571.700000,534.300000,573.1,3.25,4.50,1.50,1.00,1.25
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,13032,35410,1,blkTestCatAAp,33,1,2000,Approach,1,967,...,900.200000,0.0,926.550000,968.450000,0.0,2.50,4.75,2.25,3.50,2.75
355,13072,35510,1,blkTestCatAAp,35,1,800,Approach,1,868,...,678.200000,0.0,690.473684,732.235294,0.0,3.00,4.50,1.00,2.50,2.25
356,13108,35610,1,blkTestCatAAp,49,2,1000,Avoid,1,658,...,786.100000,0.0,704.947368,613.450000,0.0,4.00,4.25,1.25,3.00,1.75
357,13147,35710,1,blkTestCatAAp,32,1,1400,Approach,1,2361,...,1728.125000,0.0,1678.071429,1054.300000,0.0,4.00,2.50,2.25,3.75,1.50
358,13181,35810,1,blkTestCatAAp,58,2,1100,Avoid,1,1145,...,980.100000,0.0,1002.400000,857.850000,0.0,3.75,3.50,3.25,3.75,2.25

In [138]:
# make copy of names_dataset
names_dataset = names_dataset.copy()

# Add '0' as the first digit to ensure all values have 5 digits in Zip
faces_dataset.loc[faces_dataset["Zip"].astype(str).str.len() < 5, "Zip"] = faces_dataset["Zip"].astype(str).str.zfill(5)

# reset index after filtering
names_dataset.reset_index(drop=True, inplace=True)

In [139]:
# Convert 'NAME' column in final and 'Zip' column in faces_dataset to int64
final['NAME'] = final['NAME'].astype('int64').copy()
names_dataset['Zip'] = names_dataset['Zip'].astype('int64').copy()

/var/folders/z2/38w7d0t53n9_7n4mywgz6phc0000gn/T/ipykernel_1811/3247987201.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final['NAME'] = final['NAME'].astype('int64').copy()

In [140]:
# Merge datasets based on 'Zip' column with a left join
merged_names = pd.merge(names_dataset, final, left_on='Zip', right_on='NAME', how='left')

# Update 'white_black' values where there's a match
merged_names['white_black'] = merged_names['white_black'].fillna(0)  # Fill NaN values with 0

# Drop the extra 'NAME' column
merged_names.drop(columns=['NAME'], inplace=True)

merged_names

,Unnamed: 0.1,Unnamed: 0,block_order,block_name,stimuli,valence,random_fixation,movement,accuracy,response_time,...,Avg Total RT Avoid Black,Avg Total RT Approach White,Avg Total RT Avoid White,Openness,Conscientiousness,Extraversion,Agreeableness,Neuroticism,white_black,diversity_index
0,0,10,1,blkTestCatAAp,40,1,1200,Avoid,1,653,...,705.300000,906.700000,721.8,4.00,3.75,3.00,3.50,3.00,197.511628,0.102805
1,40,110,1,blkTestCatAAp,61,2,1900,Approach,1,6601,...,1192.500000,1236.200000,1417.3,3.50,4.00,4.25,3.25,2.50,2.708221,0.589204
2,80,210,1,blkTestCatAAp,34,1,1900,Avoid,1,1262,...,1028.000000,951.875000,1231.5,3.50,3.50,3.25,2.25,3.00,0.267080,0.483474
3,113,310,1,blkTestCatAAp,47,2,1000,Approach,1,1895,...,694.300000,761.200000,735.1,3.75,4.75,4.50,4.75,2.50,0.107983,0.368624
4,153,410,1,blkTestCatAAp,49,2,1300,Approach,1,415,...,571.700000,534.300000,573.1,3.25,4.50,1.50,1.00,1.25,0.026607,0.138734
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
354,13032,35410,1,blkTestCatAAp,33,1,2000,Approach,1,967,...,926.550000,968.450000,0.0,2.50,4.75,2.25,3.50,2.75,inf,0.052877
355,13072,35510,1,blkTestCatAAp,35,1,800,Approach,1,868,...,690.473684,732.235294,0.0,3.00,4.50,1.00,2.50,2.25,227.333333,0.084380
356,13108,35610,1,blkTestCatAAp,49,2,1000,Avoid,1,658,...,704.947368,613.450000,0.0,4.00,4.25,1.25,3.00,1.75,4.424026,0.547393
357,13147,35710,1,blkTestCatAAp,32,1,1400,Approach,1,2361,...,1678.071429,1054.300000,0.0,4.00,2.50,2.25,3.75,1.50,9.089725,0.486579
358,13181,35810,1,blkTestCatAAp,58,2,1100,Avoid,1,1145,...,1002.400000,857.850000,0.0,3.75,3.50,3.25,3.75,2.25,8.851143,0.399236

In [41]:
# write merged data
merged_names.to_csv('merged_names.csv', index=False)